[server]
port = 9013

[mysql]
dsn = "exam:exam123@tcp(192.168.137.2:3306)/track?charset=utf8mb4&parseTime=True&loc=Local"

[redis]
addr = "192.168.137.2:6379"
password = "redis"
db = 0

[log]
filepath = "log/EduLimitRate.log"
max_size = 50       # 单个文件最大大小（MB）
max_backups = 10    # 最多保留旧文件数
max_age = 7         # 最多保留天数
compress = true     # 是否压缩
